# Site settings
title: Max Lei ZHAO
SEOTitle: Lei ZHAO | 赵磊
header-img: img/post-bg-desk.jpg
email: zhaolei19@mails.ucas.ac.cn
description: ""
keyword: "Lei Zhao, Zhao Lei, 赵磊"
url: "https://maxandyuki.github.io"          # your host, for absolute URL
baseurl: "I hope there will be unexpected surprises in autumn."      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/maxandyuki/maxandyuki.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "ᴮᵉᶜᵃᵘˢᵉ ᵗᵒᵐᵒʳʳᵒʷ ᶜᵃⁿ ᵇᵉ ᵉˣᵖᵉᶜᵗᵉᵈ, ˢᵒ ᵗʰⁱˢ ˡⁱᶠᵉ ʷⁱˡˡ ⁿᵒᵗ ᵇᵉ ᵃᵇᵃⁿᵈᵒⁿᵉᵈ."
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     qiubaiying
github_username:    qiubaiying
facebook_username:  baiying.qiu.7
jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: cc56c004c94aa9bb620b                            #生成的clientID
  clientSecret: 2c6cb42f93704dbd3d7519dd4906f898c2ed1bb2    #生成的clientSecret
  repo: MaxandYuki.github.io    #仓库名称
  owner: MaxandYuki    #github用户名
  admin: MaxandYuki
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 08a8d8cee063ee14c2b949a021c1d433

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
